# Dependabot configuration file options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/quasiquodo"
      - "/quasiquodo-ts-core"
      - "/quasiquodo-ts-macros"
    schedule:
      interval: "weekly"
