# Dependabot configuration file options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      swc:
        patterns:
          - "swc_*"
      ruff:
        patterns:
          - "ruff_*"
